(* ::Package:: *)

(* ::Title:: *)
(*SubTropica notebook: Bubble*)

(* ::Text:: *)
(*Auto-generated by subtropi.ca on 2026-04-15T03:45:01.680Z.
Schema: case-iii (entry with result)
Generator version: 0.1.0*)

(* ::Text:: *)
(*This notebook is a self-contained starting point for computing the Feynman integral above with SubTropica. Evaluate the cells top-to-bottom. Everything runs inside Mathematica 13.1+; external tools (polymake, pySecDec, AMFlow, feyntrop, FIRE, LiteRed) are optional and only needed where noted.*)

(* ::Section:: *)
(*Install SubTropica*)

(* ::Subsection:: *)
(*One-time install*)

(* ::Text:: *)
(*Clones the SubTropica repository into your home directory if it is not already there, and adds it to $Path. Evaluate this cell exactly once. You can also install manually by cloning https://github.com/SubTropica/SubTropica yourself.*)

If[!DirectoryQ[FileNameJoin[{$HomeDirectory, "SubTropica"}]],
	Print["Cloning SubTropica into ", FileNameJoin[{$HomeDirectory, "SubTropica"}], "..."];
	RunProcess[{"git", "clone", "https://github.com/SubTropica/SubTropica.git",
		FileNameJoin[{$HomeDirectory, "SubTropica"}]}]
];
If[!MemberQ[$Path, FileNameJoin[{$HomeDirectory, "SubTropica"}]],
	PrependTo[$Path, FileNameJoin[{$HomeDirectory, "SubTropica"}]]
];

(* ::Subsection:: *)
(*Load the package (every session)*)

(* ::Text:: *)
(*Evaluate this in every fresh Mathematica session before using any ST* functions. The $IterationLimit bump works around a benign issue in the package's startup path resolution on some fresh kernels.*)

$IterationLimit = 10^6;
Get["SubTropica`"];

(* ::Subsection:: *)
(*Optional: configure external tools*)

(* ::Text:: *)
(*polymake is required for the full tropical pipeline (macOS: brew install polymake; Linux: see https://polymake.org/install). FiniteFlow and SPQR are recommended for large problems. ginsh is optional for numerical hyperlogarithms. PythonPath must point at a Python interpreter with pySecDec installed (pip install pySecDec, typically inside a dedicated venv) if you plan to use the pySecDec backend of STNIntegrate below.*)

(* ConfigureSubTropica[
	PolymakePath   -> "/opt/homebrew/bin/polymake",
	PythonPath     -> FileNameJoin[{$HomeDirectory, ".venvs/subtropica312/bin/python"}],
	FiniteFlowPath -> "path/to/FiniteFlow",
	SPQRPath       -> "path/to/SPQR",
	GinshPath      -> "path/to/ginsh"
]; *)

(* ::Section:: *)
(*Graph definition*)

(* ::Text:: *)
(*Edges carry internal-propagator masses; nodes carry external momenta attached at vertices. Notation: m[i] for internal masses, M, M1, M2, \[Ellipsis] for external-leg masses (Sqrt of squared external momenta).*)

edges = {{{1, 2}, m[1]}, {{1, 2}, m[2]}};
nodes = {{1, M}, {2, M}};

(* ::Text:: *)
(*Quick visualization. FeynmanPlot ships with SubTropica; we'll drop a pixel-exact SVG rendering from subtropi.ca in this slot in a future revision.*)

FeynmanPlot[{edges, nodes}, "LabelInternalEdges" -> True]

(* ::Section:: *)
(*Analytic evaluation with STIntegrate*)

(* ::Text:: *)
(*Single call, graph form. STIntegrate runs the full pipeline: gauge-fixing, Newton-polytope analysis, tropical subtraction, and hyperlogarithm integration. Defaults below: d = 4 - 2 eps, expand through eps^0, all propagator exponents = 1. "FindRoots" -> True enables fibered rationalization, which is needed whenever the integrand's linear reducibility analysis otherwise fails.*)

result = STIntegrate[{edges, nodes},
	"FindRoots" -> True,
	"MethodLR" -> "Lungo"];

(* ::Subsection:: *)
(*Library reference result*)

(* ::Text:: *)
(*This integral already has a published result in the SubTropica library (SubTropica v1.0.281, contributor: Sebastian Mizera). The cell below loads it for comparison.*)

referenceResultTeX = "\\frac{1}{\\varepsilon}+\\left(\\frac{\\log \\left(-\\frac{1}{2} m_2^{-2} \\left(-\\sqrt{\\left(-m_1^2-m_2^2+M^2\\right)^2-4 m_1^2 m_2^2}-m_1^2-m_2^2+M^2\\right)\\right)}{\\frac{1}{2} m_2^{-2} \\left(-\\sqrt{\\left(-m_1^2-m_2^2+M^2\\right)^2-4 m_1^2 m_2^2}-m_1^2-m_2^2+M^2\\right)+1}+\\frac{\\log \\left(-\\frac{1}{2} m_2^{-2} \\left(\\sqrt{\\left(-m_1^2-m_2^2+M^2\\right)^2-4 m_1^2 m_2^2}-m_1^2-m_2^2+M^2\\right)\\right)}{\\frac{1}{2} m_2^{-2} \\left(\\sqrt{\\left(-m_1^2-m_2^2+M^2\\right)^2-4 m_1^2 m_2^2}-m_1^2-m_2^2+M^2\\right)+1}-\\log \\left(m_1^2\\right)+2\\right)+O\\left(\\varepsilon^1\\right)";

(* ::Text:: *)
(*To compare analytically, load the compressed expression:*)

referenceResult = Uncompress["1:eJztU9sKwjAM7S6K+Bf+i48bjOkPVOgksFlZNvx5QdMWh6mrPulDsQ+nNDk9PWnI5qDrZimEwDXBTvWgcCsHiRkd1RmBNtGkhpATFIADJCaUP0JVOyKkE2tBsIdOIdxoNYZrtQp9dAfD6jonwm9wcsZzlroiqOUA+iRbq+89XOmL6tkzZnNOmGGbLsuw5bDLV1KweM9X+uzAT2Zftec88i+F66zcfGXs55NJ8V2FTu5jG4Ni/zb+qo1emRENY6wdi3jwYm2ZGxELNmbgDrT2sLU="];

(* ::Text:: *)
(*Symbol alphabet (weight 1, 4 terms):*)

referenceAlphabet = {
  "W_1",
  "W_2",
  "W_3"
};

(* ::Text:: *)
(*Normalized letters W_i are defined in terms of the physical scales as:*)

wDefinitions = {
  <|"label" -> "W_1", "definitionTeX" -> "\\frac{m_2^2}{m_1^2}", "originalLetterTeX" -> "m_2^2"|>,
  <|"label" -> "W_2", "definitionTeX" -> "\\frac{-M^2+m_1^2+m_2^2+\\sqrt{\\left(M^2-m_1^2-m_2^2\\right)^2-4 m_1^2 m_2^2}}{m_1^2}", "originalLetterTeX" -> "\\sqrt{\\left(-m_1^2-m_2^2+M^2\\right)^2-4 m_1^2 m_2^2}+m_1^2+m_2^2-M^2"|>,
  <|"label" -> "W_3", "definitionTeX" -> "\\frac{-M^2+m_1^2+m_2^2-\\sqrt{\\left(M^2-m_1^2-m_2^2\\right)^2-4 m_1^2 m_2^2}}{m_1^2}", "originalLetterTeX" -> "-\\sqrt{\\left(-m_1^2-m_2^2+M^2\\right)^2-4 m_1^2 m_2^2}+m_1^2+m_2^2-M^2"|>
};

(* ::Text:: *)
(*Side-by-side check. The difference should simplify to 0 when your integration succeeds and uses the same variable conventions. If your STIntegrate above returned $Aborted (e.g. no linearly reducible order was found for the default settings), only the library result is meaningful — the difference line is not.*)

Column[{
	Style["Your result:", Bold], result,
	Style["Library result:", Bold], referenceResult,
	Style["Difference (should simplify to 0):", Bold],
	If[MemberQ[{$Aborted, $Failed, Null}, result],
		Style["(skipped: your integration did not return a usable result)", Italic, Gray],
		Simplify[result - referenceResult /. {Wm[1] -> (MM - mm[1] - mm[2] + Sqrt[(MM - mm[1] - mm[2])^2 - 4*mm[1]*mm[2]])/(2*mm[2]), Wp[1] -> (MM - mm[1] - mm[2] - Sqrt[(MM - mm[1] - mm[2])^2 - 4*mm[1]*mm[2]])/(2*mm[2])}]
	]
}]

(* ::Section:: *)
(*Numerical evaluation*)

(* ::Text:: *)
(*STNIntegrate provides four backends. Uncomment the one you want. All return an association with Value, Error, Method, and Timing. The kinematic point below is a Euclidean sample; adjust for your physics.*)

substitutions = {mm[1] -> 1, mm[2] -> 1, MM -> -1};

(* pySecDec (default, sector decomposition) *)
STNIntegrate[{edges, nodes},
	"Method" -> "pySecDec",
	"Substitutions" -> substitutions
]

(* AMFlow (auxiliary-mass flow, needs FIRE or Kira) *)
(* STNIntegrate[{edges, nodes},
	"Method" -> "AMFlow",
	"Substitutions" -> substitutions
] *)

(* feyntrop (tropical Monte Carlo, finite integrals only) *)
(* STNIntegrate[{edges, nodes},
	"Method" -> "feyntrop",
	"Substitutions" -> substitutions
] *)

(* FIESTA (sector decomposition, Mathematica-side) *)
(* STNIntegrate[{edges, nodes},
	"Method" -> "FIESTA",
	"Substitutions" -> substitutions
] *)

(* ::Section:: *)
(*IBP & master integrals (optional)*)

(* ::Text:: *)
(*SubTropica does not perform IBP reduction, but after STIntegrate above has run, the routed k-space propagators live in the global $STPropagators. Inspect them and identify which symbols are loop momenta (e.g. k, k1, k2) versus external momenta (e.g. p, p1, p2):*)

Print["Propagators (routed): ", $STPropagators];
Print["Symbols present: ", Variables[$STPropagators]];

(* ::Subsection:: *)
(*LiteRed (topology analysis, master count)*)

(* ::Text:: *)
(*Uncomment if LiteRed is installed. Adjust the Internal/External split to match the symbols printed above.*)

(* Needs["LiteRed`"];
Internal = {k};
External = {p};
NewBasis[familybxf209604c178e, $STPropagators, Internal,
	Directory -> FileNameJoin[{$TemporaryDirectory, "familybxf209604c178e"}]];
AnalyzeSectors[familybxf209604c178e];
FindSymmetries[familybxf209604c178e];
Length[IBPBasis[familybxf209604c178e]]   (* number of masters *) *)

(* ::Subsection:: *)
(*FIRE (IBP reduction to masters)*)

(* ::Text:: *)
(*Uncomment if FIRE6 is installed. Adjust Internal/External and Replacements for your kinematics.*)

(* Get["FIRE6`"];
Internal = {k};
External = {p};
Propagators = $STPropagators;
PrepareIBP[];
Replacements = {p^2 -> M^2};
Prepare[AutoDetectRestrictions -> True];
F[1, ConstantArray[1, Length[Propagators]]]   (* target integral, all exponents = 1 *) *)

(* ::Section:: *)
(*References*)

(* ::Text:: *)
(*This topology appears in the following works:*)

(* ::Program:: *)
(*
  [1] arXiv:0712.1851
  [2] arXiv:0712.1851 (JHEP 02 (002), 2008)
  [3] arXiv:1610.08397 (Nucl.Phys.B 916 (94), 2017)
  [4] arXiv:2209.10962 (Lett.Math.Phys. 113 (37), 2023)
  [5] arXiv:2211.01285 (Comput.Phys.Commun. 287 (), 2023)
  [6] arXiv:2502.19168
  [7] arXiv:2510.26874
  [8] arXiv:2412.15962
  [9] arXiv:2508.04309
*)

(* ::Subsection:: *)
(*BibTeX (fetched from INSPIRE)*)

(* ::Program:: *)
(*
@article{Ellis:2007qk,
  note = "not found on INSPIRE — retrieve manually: https://inspirehep.net/literature?q=texkey:Ellis:2007qk"
}

@article{Primo:2016ebd,
  note = "not found on INSPIRE — retrieve manually: https://inspirehep.net/literature?q=texkey:Primo:2016ebd"
}

@article{Lairez:2022zkj,
  note = "not found on INSPIRE — retrieve manually: https://inspirehep.net/literature?q=texkey:Lairez:2022zkj"
}

@article{Ananthanarayan:2022ntm,
  note = "not found on INSPIRE — retrieve manually: https://inspirehep.net/literature?q=texkey:Ananthanarayan:2022ntm"
}

@article{Wang:2024hsm,
  note = "not found on INSPIRE — retrieve manually: https://inspirehep.net/literature?q=texkey:Wang:2024hsm"
}
*)

(* ::Section:: *)
(*Metadata*)

(* ::Program:: *)
(*
  CNickelIndex       : e11|e|:012|0|
  recordId (primary) : bx_f209604c178e
  SubTropica version : SubTropica v1.0.281
  Library commit     : unknown
  Generated          : 2026-04-15T03:45:01.680Z
  Case               : iii (entry with result)
*)
